version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: monthly
