CREATE TABLE IF NOT EXISTS FAIL2BAN (
    ID BIGINT,
    IP VARCHAR(255),
    ISP VARCHAR(255),
    CITY VARCHAR(255),
    ZIP VARCHAR(255),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PRIMARY KEY (ID)
);
