version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: sqlite
    container_name: fail2ban-monitoring-sqlite
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      # - Link the logs file here

volumes:
  data: