version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: fail2ban-monitoring-postgres
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=fail2ban
      - DB_PASSWORD=fail2banpassword
      - DB_NAME=fail2ban
    volumes:
      - ./config:/app/config
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: fail2ban-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=fail2ban
      - POSTGRES_PASSWORD=fail2banpassword
      - POSTGRES_DB=fail2ban
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: