{
 "title": "fail2ban - xiao",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Ataques por ciudad",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lat,\n  lng,\n  city,\n  count(city) as \"ciudades\",\n  ip as \"metric\"\nFROM ips\nWHERE\n  $__timeFilter(time)\ngroup by city"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  city,\n  count(city) as \"metrica\"\n  \nFROM Grafana.ips \ngroup by city"
    }
   ]
  },
  {
   "title": "Ataques por pais",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 11, "x": 10, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  avg(lat) as \"lat\",\n  avg(lng) as \"lng\",\n  country,\n  count(country) as \"paises\",\n  ip as \"metric\"\nFROM ips\nWHERE\n  $__timeFilter(time)\ngroup by country"
    }
   ]
  },
  {
   "title": "Total IPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \ncount(country),time\nfrom ips\n"
    }
   ]
  },
  {
   "title": "Localización ataque",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 13 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  lat,\n  lng,\n  city\nFROM ips\nWHERE\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "ISPs",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 11, "x": 10, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \n  isp,\n  country,\n  count(isp) as \"isp_count\"\nFROM Grafana.ips\ngroup by country,isp\norder by isp_count desc"
    }
   ]
  }
 ]
}